app/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import main_page, login_view, register_view, post, newpost, deletepost, deletecomment
from .views import PostViewSet, CommentViewSet, CreateUserView, CustomObtainAuthToken
from .views import CustomObtainAuthToken

#Urls de la api de post y comentarios
router = routers.DefaultRouter()
router.register(r'posts', PostViewSet)
router.register(r'comments', CommentViewSet)

app_name = 'nombreApp'
urlpatterns = [
    path('', main_page, name='index'),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('post/<int:id>', post, name='post'),
    path('newpost/', newpost, name='newpost'),
    path('post/deletepost/<int:id>', deletepost, name='deletepost'),
    path('post/deletecomment/<int:id>', deletecomment, name='deletecomment'),
    path('api/', include(router.urls)),  # Rutas de la API
    path('api/register/', CreateUserView.as_view(), name='register'),
    path('api/login/', CustomObtainAuthToken.as_view(), name='login'),
]

proyecto/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    userId  = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=50)
    info = models.CharField(max_length=1250)
    creation_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    userId = models.ForeignKey(User, on_delete=models.CASCADE, default=1) 
    postId  = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.CharField(max_length=255)
    creation_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.comment

class Category(models.Model):
    category_name = models.CharField(max_length=20)
    postId  = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.category_name

app/templates/app/base.html
<!doctype html>
<html lang="en" class="bg-warning">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Bootstrap demo</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous"> 
    </head>
    <nav class="text-white bg-dark" style="top: 0;left: 0; margin-bottom: 15px;">
        <div class="row" style="max-width: 99%;">
            <div class="col-1 invisible"></div>
            <div class="col-2"><h4><a href="/" class="text-white text-decoration-none">  PIPS DJANGO!  </a></h4></div>
            <div class="col-9 mt-1">
                {% block users%}
                {% endblock %}
            </div>
        </div>
    </nav> 
    {% block marquee %}
    {% endblock %}
    {% block index %}
    {% endblock %}
    {% block secondary%}
    {% endblock %}
</html>

app/templates/app/category.html
{% extends 'app/index.html' %}

{% block contenido %}
        <div class="container">  
            <div class="row">
                <div>
                    {{categories.name}}
                    {% for c in categories %}
                        <h4>{{ c.categories.name }}</h4>
                    {% endfor  %}
                </div>
            </div>
        </div>
{% endblock %}

app/templates/app/delete_comment.html
{% extends 'app/index.html' %}

{% block contenido %}
<div style="margin-top: -15px;">
    <h1>userid:{{ user.id }}</h1> 
    <div class="container">   
        <div class="row">  
            <div class="card-body rounded bg-dark text-light">
                <h1 style="margin-left: 10px;">Delete Post!</h1>
                <hr>
                <form class="text-center" action="" method="post">
                    
                    <button type="submit" class="btn btn-danger">Delete!</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/delete_post.html
{% extends 'app/index.html' %}

{% block contenido %}
<div style="margin-top: -15px;">
    <h1>userid:{{ user.id }}</h1> 
    <div class="container">   
        <div class="row">  
            <div class="card-body rounded bg-dark text-light">
                <h1 style="margin-left: 10px;">Delete Post!</h1>
                <hr>
                <form class="text-center" action="" method="post">
                    
                    <button type="submit" class="btn btn-danger">Delete!</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/deletepost.html
{% extends 'app/index.html' %}

{% block contenido %}
<div style="margin-top: -15px;">
    <h1>userid:{{ user.id }}</h1> 
    <div class="container">   
        <div class="row">  
            <div class="card-body rounded bg-dark text-light">
                <h1 style="margin-left: 10px;">Delete Post!</h1>
                <hr>
                <form class="text-center" action="" method="post">
                    
                    <button type="submit" class="btn btn-danger">Delete!</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}

{% block users %}
    <div class="row text-right" style="width: 100%;">
        <div class="col-8 invisible"></div>
        {% if user.is_authenticated %}
            {% block newpost %}
            {% endblock %}
            <div class="col-1 bg-success border rounded border-dark">
                <h6>User:{{ user.username }}</h6>
            </div>
            <div class="col-1 bg-danger border rounded border-dark">
                <h6 ><a class="text-center text-decoration-none text-white" href="{% url 'logout' %}">Logout</a></h6>
            </div>
        {% else %}
            <div class="col-2">
                <h6><a class="text-center  text-decoration-none text-white bg-" href="{% url 'login' %}">Login</a></h6>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block index %}
  <body class="bg-warning">
    <div class="container">
        <div class="row">
            <div class="col-3 bg-dark text-white border-dark rounded">
                <div  style="padding-left: 15px;">
                    <h4 class=" text-center mt-1 mb-3">Categorias</h4>
                        {% for c in categories %}
                            <h5 class="mt-1 border border-white bg-secondary text-center">{{ c.category_name }} </h5>
                        {% endfor %}
                </div>    
            </div>
            <div class="col-9">        
                {% block contenido %}
                {% endblock %}
            </div>  
        </div>
    </div>
</div>
</body>
{% endblock %}

app/templates/app/main_page.html
{% extends 'app/index.html' %}
{% if user.is_authenticated %}
    {% block newpost %}
        <div class="col-2">
            <a href="newpost" class="btn btn-success">Crear un post!</a>
        </div>
    {% endblock %}
{% endif %}

{% block contenido %}
        <div class="container">  
            <div class="row bg-dark text-white border-dark border-top rounded-top">
                <div class="col-9 text-center"><h2>Titulo</h2></div>
                <div class="col-3 text-center"><h2>Fecha</h2></div>
            </div>
            <div class="row border border-dark rounded-bottom">
                {% for p in posteos %}
                    <div class="col-9 text-left bg-secondary"><a class="text-decoration-none text-dark" href="post/{{ p.id }}"><h3 class="mt-1 display-6">{{ p.title }} </h3></div></a> 
                    <div class="col-3 text-center bg-primary"><h3 class="mt-1 display-6">{{ p.creation_date }}</h3></div>
                    <div class="col-12 invisible">Espacio</div>
                {% endfor %}
            </div>
    </div>
</div>
{% endblock %}

app/templates/app/new_post.html
{% extends 'app/index.html' %}

{% block contenido %}
<div >
    <div class="container">   
        <div class="row">  
            <div class="card-body rounded bg-dark text-light">
                <h1 style="margin-left: 10px;">New Post!</h1>
                <hr>
                <form class="text-center" action="" method="POST">
                    {% csrf_token %}
                    <div class="invisible">
                        <tr>
                            <th><label for="id_userId">UserId:</label></th>
                                <select name="userId" required id="id_userId"><option value="{{user.id}}" selected>{{user.username}}</option></select>
                            </td>
                        </tr>
                    </div>
                    <div class="col-12">
                        <tr>
                            <h4><th><label for="id_title">Titulo</label></th></h4>
                            <td>
                                <h6><input type="text" name="title" value="" maxlength="50" required id="id_title" style="height: 25px;"><h6>
                            </td>
                        </tr>
                    </div>
                    <div class="col-12">
                        <tr>
                            <h4><th><label for="id_info">Info</label></th></h4>
                            <td>
                            <input type="text" name="info" value="" maxlength="1250" required id="id_info">
                            </td>
                        </tr>
                    </div>
                    
                    <button type="submit" class="btn btn-success mt-4 mb-4">Publicar</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/post.html
{%extends 'app/index.html'%}
{% block marquee%}
<marquee behavior="scroll" direction="right" class="bg-primary " scrolldelay="300" scrollamount="150" style="max-height: 30px; font-size: 25px;">
    <div class="text-white">
        <pre >POSTEOS!       POSTEOS!       POSTEOS!       POSTEOS!       POSTEOS!       POSTEOS!       POSTEOS!       POSTEOS!       POSTEOS!       POSTEOS!</pre>               
    </div>
</marquee>
{% endblock %}

{%block contenido%}
<div class="conteiner bg-warning" style="margin-left: 10px;">
    <div class="row">
        <h2 class="text-center col-9  display-6" path>{{post.title}}</h2>
    </div>
    <hr>
    <div class="row bg-light border border-dark rounded">
        <div class="col-9" > 
            <h5 style="text-align: justify;" >{{post.info}} </h5>
        </div>
        <div class="col-3 bg-dark text-white border border-dark rounded" style="padding: 1%;">
            <h6 class="text-end mt-2">Fecha de subida: {{post.creation_date}}</h6>
            <h4 class="text-white mt-2  bg-primary text-center border-primary">Autor: {{post.userId}} </h4>
            <div>
                <h6 class="text-center mt-2"> Categorias </h6>
                {% for c in categories2 %}
                        <h6 class="text-center bg-white text-dark mt-2">{{c.category_name}}</h6>
                {% endfor %}
                {% if user.is_authenticated %}
                    {% if user.id == owner %}
                    <div class="text-center bg-danger ">
                        <a href="deletepost/{{ postId }}" class="text-white text-decoration-none">Borrar este post!</a>
                    </div>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    <br>
</div>
<div class="container bg-secondary"></div>
        {% if user.is_authenticated %}
            <form class="text-center row" style="margin-left: 5px;" action="" method="post">
                {% csrf_token %}
                <div class="invisible col-6">
                    <tr>
                        <th><label for="id_userId">UserId:</label></th>
                            <select name="userId" required id="id_userId"><option value="{{user.id}}" selected>{{user.username}}</option></select>
                        </td>
                    </tr>
                </div>
                <div class="invisible col-6">
                    <tr>
                        <th><label for="id_postId">PostId:</label></th>
                            <select name="postId" required id="id_postId"><option value="{{postId}}" selected>{{postId}}</option></select>
                        </td>
                    </tr>
                </div>
                <h4>Publica un comentario!</h4>
                    {{data.form.comment}}
                <div class="col-12 mt-1" style="width: 100%;"><button type="submit" class="btn btn-success">Publicar</button></div>
            </form>
        {% endif %}
        <div class="row"  style="margin-left: 10px;">
            <hr class=" mt-3">
            <div class="text-center"><h4>Comentarios</h4></div> 
            {% for c in comments %}
                <h6 class="col-2 mt-1 text-center bg-primary border border-primary rounded-left text-white" style="border-top-left-radius: 3px; border-bottom-left-radius: 3px;">{{ c.creation_date }}</h6>
                <h5 class="col-7 mt-1 bg-secondary text-white">{{ c.comment }}</h5>
                <h6 class="col-2 mt-1 bg-dark text-white border border-dark" style="border-top-right-radius: 3px; border-bottom-right-radius: 3px; padding-left: 5px; padding-right: 5px;">{{ c.userId }}</h6>
                <div class="col-1">
                    {% if c.userId.id == user.id %}
                    <div>
                        <a href="deletecomment/{{c.id}}" class="btn btn-danger">eliminar</a>
                    </div>
                    {% endif%}
                </div>
                
            {% endfor %}
        </div> 
    </div>
</div>
{%endblock%}

    
   
 

app/templates/app/register.html
{%extends 'app/base.html' %}

{% block index %}
<div class="bg-warning" style="margin-top: -15px;">
    <div class="container text-center">
        <div class="row">
            <br>
            <div class="col-6 offset-md-3">
                <div class="card mt-5">
                    <div class="card-body rounded bg-dark text-light">
                        <h1>Register</h1>
                        <hr>
                        <form action="" class="" method="post">
                            {% csrf_token %}
                            {{ form }}
                            <hr>
                                <button type="submit" class="btn btn-success btn-lg btn-block">Register</button>                       
                        </form>
                    {{mensaje}}
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}